### ISSUE TITLE
How can I serialize my own user-defined-types?

### ISSUE THREAD

**Issue by buaaCCJ** [usagi/cereal-UE4#1]
How to serialize this situation in which FSymmetryBone and FUnsymmetryBone are the struct defined by myself. Thanks.
![_20180625112539](https://user-images.githubusercontent.com/20292463/41829012-ef48b720-786a-11e8-9c4a-5d61fabf840d.png)

**Comment by usagi** [comment]
`FSymmetryBone` and `FUnsymmetryBone` are not supported types in this adapter library *YET*. ( see also cereal-UE4 suported types in README.md )

And, I am sorry for you long time waiting. I got a time in now. I'll research the implementations of these types and support these types if I can.

**Comment by usagi** [comment]
> the struct defined by myself

Ah, that is not a cereal-UE4 issue, it's your studying issue of cereal. You can implement cereal adaptors for your user-defined-types with these cereal docs. And you may also refer to source codes in this repos about how to implement user-defined-types.

- <http://uscilab.github.io/cereal/quickstart.html>
- <https://github.com/usagi/cereal-UE4/blob/master/include/cereal-UE4/FColor.hxx>

Sorry for keeping you waiting for a long time. Cheers.
